[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[functions]
  included_files = ["node_modules/.geo/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
